apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - "{{ .Release.Name }}.{{ .Values.ingress.base_host }}"
  rules:
  - host: "{{ .Release.Name }}.{{ .Values.ingress.base_host }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 9292
